
import { useEffect, useState, useCallback } from "react";
import { cn } from "@/lib/utils";
import { List } from "lucide-react";

interface Heading {
  id: string;
  text: string;
  level: number;
}

interface TableOfContentsProps {
  content: string;
  containerSelector?: string;
  onLinkClick?: () => void;
  onHeadingsFound?: (hasHeadings: boolean) => void;
}

export function TableOfContents({
  content,
  containerSelector = ".prose",
  onLinkClick,
  onHeadingsFound,
}: TableOfContentsProps) {
  const [headings, setHeadings] = useState<Heading[]>([]);
  const [activeId, setActiveId] = useState<string>("");

  // Extract headings from rendered DOM to ensure IDs match rehype-slug output
  const extractHeadingsFromDOM = useCallback(() => {
    const container = document.querySelector(containerSelector);
    if (!container) return [];

    const elements = container.querySelectorAll("h2, h3");
    const extracted: Heading[] = [];

    elements.forEach((el) => {
      const id = el.id;
      const text = el.textContent?.trim() || "";
      const level = parseInt(el.tagName.charAt(1), 10);
      if (id && text) {
        extracted.push({ id, text, level });
      }
    });

    return extracted;
  }, [containerSelector]);

  useEffect(() => {
    // Wait for content to render, then extract headings from DOM
    // This ensures we get the actual IDs generated by rehype-slug
    const timer = setTimeout(() => {
      const extractedHeadings = extractHeadingsFromDOM();
      setHeadings(extractedHeadings);

      // Notify parent if headings exist
      if (onHeadingsFound) {
        onHeadingsFound(extractedHeadings.length > 0);
      }
    }, 150); // Small delay to ensure content is rendered

    return () => clearTimeout(timer);
  }, [content, extractHeadingsFromDOM, onHeadingsFound]);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        });
      },
      { rootMargin: "-10% 0px -80% 0px" },
    );

    const elements = headings
      .map((h) => document.getElementById(h.id))
      .filter(Boolean);
    elements.forEach((el) => el && observer.observe(el));

    return () => {
      elements.forEach((el) => el && observer.unobserve(el));
    };
  }, [headings]);

  if (headings.length === 0) return null;

  const handleClick = (e: React.MouseEvent<HTMLAnchorElement>, id: string) => {
    e.preventDefault(); // CRITICAL: Stop browser from auto-jumping/updating URL hash

    const element = document.getElementById(id);
    if (element) {
      const headerOffset = 100; // Offset for sticky header
      const elementPosition = element.getBoundingClientRect().top;
      const offsetPosition = elementPosition + window.scrollY - headerOffset;

      window.scrollTo({
        top: offsetPosition,
        behavior: "smooth",
      });

      setActiveId(id);
      if (onLinkClick) onLinkClick();
    }
  };

  return (
    <nav className="space-y-2 text-sm">
      <div className="flex items-center gap-2 mb-4 text-primary font-mono text-xs uppercase tracking-widest font-bold">
        <List className="h-4 w-4" />
        Table of Contents
      </div>
      <div className="relative pl-3">
        {/* Vertical line track */}
        <div className="absolute left-0 top-0 bottom-0 w-px bg-border" />

        <ul className="space-y-3">
          {headings.map((heading) => (
            <li key={heading.id} className="relative">
              {/* Active Indicator */}
              {activeId === heading.id && (
                <div className="absolute -left-[13px] top-1.5 h-4 w-0.5 bg-primary rounded-full transition-all duration-300" />
              )}

              <a
                href={`#${heading.id}`}
                onClick={(e) => handleClick(e, heading.id)}
                className={cn(
                  "block text-left transition-colors duration-200 line-clamp-2 leading-snug hover:text-primary focus:outline-none",
                  heading.level === 3 && "ml-4 text-xs",
                  activeId === heading.id
                    ? "text-primary font-medium translate-x-1"
                    : "text-muted-foreground",
                )}
              >
                {heading.text}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </nav>
  );
}
